### PR TITLE
:arrow_up: Upgrade to Vite 6

### PR DESCRIPTION
**Pull request by sergei-maertens**
Released a couple of weeks ago :)

### CODE REVIEW

**Comment by sergei-maertens** [comment]
Blocked by https://github.com/storybookjs/storybook/issues/29719 :)

**Comment by sergei-maertens** [comment]
Workaround applied from pinned Storybook issue.

**Comment by sergei-maertens** [comment]
@robinmolen @vaszig considering this is build tooling and CI is passing, I think it's not too extreme to merge this in main before the 2.5.0 release, but feel free to disagree if you think it's too risky!

**Review by vaszig — COMMENTED** [review]
I am not familiar with this, especially the new version, but if Robin agrees of course we can merge it!

**Comment by sergei-maertens** [comment]
I'm going to go ahead with this, otherwise this PR remains open too long while people are on vacation.

The Vite toolchain is not used yet in critical aspects (i.e. the production build of the SDK).

**Pull request merged**
