### PR TITLE
[OF#2907] Avoid clipping title with ellipsis

### PR DESCRIPTION
**Pull request by SilviaAmAm**
Fixes open-formulieren/open-forms#2907

### CODE REVIEW

**Review by CharString — COMMENTED** [review]
Looks fine to me.
Should we point out the existence of soft hyphen to form builders in our documentation?

And is `&__title` applied in the location mentioned in 96602972

**Comment by SilviaAmAm** [comment]
The behaviour of the progress indicator on mobile and in the pause modal is maintained:
Screenshot from 2023-03-20 13-09-14
Screenshot from 2023-03-20 13-09-34
Screenshot from 2023-03-20 13-09-45
(Although maybe also the pause modal should not be clipped?)

**Comment by CharString** [comment]
Should we consider inserting soft hyphens?

```py
>>> import pyphen
>>> pyphen.LANGUAGES.keys()
dict_keys(['af_ZA', 'af', 'be_BY', 'be', 'bg_BG', 'bg', 'ca', 'cs_CZ', 'cs', 'da_DK', 'da', 'de_AT', 'de', 'de_CH', 'de_DE', 'el_GR', 'el', 'en_GB', 'en', 'en_US', 'eo', 'es', 'et_EE', 'et', 'fr', 'gl', 'hr_HR', 'hr', 'hu_HU', 'hu', 'id_ID', 'id', 'is', 'it_IT', 'it', 'lt', 'lv_LV', 'lv', 'mn_MN', 'mn', 'nb_NO', 'nb', 'nl_NL', 'nl', 'nn_NO', 'nn', 'pl_PL', 'pl', 'pt_BR', 'pt', 'pt_PT', 'ro_RO', 'ro', 'ru_RU', 'ru', 'sk_SK', 'sk', 'sl_SI', 'sl', 'sq_AL', 'sq', 'sr', 'sr_Latn', 'sv', 'te_IN', 'te', 'th_TH', 'th', 'uk_UA', 'uk', 'zu_ZA', 'zu'])
>>> dic = pyphen.Pyphen(lang="nl_NL")
>>> dic.inserted("ooievaarspas")
'ooi-e-vaars-pas'
>>> dic.inserted("ooievaarspas", hyphen="\u00AD")
'ooi\xade\xadvaars\xadpas'
>>> dic.inserted("aanvraagformulier ooievaarspas")
'aan-vraag-for-mu-lier ooi-e-vaars-pas'
```

**Review by CharString — APPROVED** [review]

**Comment by sergei-maertens** [comment]
Backported via 90e5ede8701e6e03bdd02bcbf94ae02de6a51580

**Pull request merged**
